export const types={
    GET_COUNTRIES: 'GET_COUNTRIES',
    GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
    GET_COUNTRIES_ERROR: 'GET_COUNTRIES_ERROR',
    ADD_COUNTRY:'ADD_COUNTRY',
    ADD_COUNTRY_SUCCESS:'ADD_COUNTRY_SUCCESS',
    ADD_COUNTRY_ERROR: 'ADD_COUNTRY_ERROR'
};